// ================= CENTRALIZED DATA FILE =================
// All data properly linked with consistent IDs

window.MovieManiacData = {
  
  // ================= ACTORS =================
  actors: [
    { id: "actor_jrntr", name: "N. T. Rama Rao Jr.", photo: "images/actors/jr ntr.jpg", industry: "Tollywood" },
    { id: "actor_ramcharan", name: "Ram Charan", photo: "images/actors/ram charan.jpg", industry: "Tollywood" },
    { id: "actor_alluarjun", name: "Allu Arjun", photo: "images/actors/allu arjun.jpg", industry: "Tollywood" },
    { id: "actor_maheshbabu", name: "Mahesh Babu", photo: "images/actors/mahesh babu.jpg", industry: "Tollywood" },
    { id: "actor_prabhas", name: "Prabhas", photo: "images/actors/prabhas.jpg", industry: "Tollywood" },
    { id: "actor_pawankalyan", name: "Pawan Kalyan", photo: "images/actors/pawan kalyan.jpg", industry: "Tollywood" },
    { id: "actor_chiranjeevi", name: "Chiranjeevi", photo: "images/actors/chiranjeevi.jpg", industry: "Tollywood" },
    { id: "actor_venkatesh", name: "Venkatesh", photo: "images/actors/venkatesh.jpg", industry: "Tollywood" },
    { id: "actor_balakrishna", name: "Balakrishna", photo: "images/actors/balakrishna.jpg", industry: "Tollywood" },
    { id: "actor_raviteja", name: "Ravi Teja", photo: "images/actors/ravi teja.jpg", industry: "Tollywood" },
    { id: "actor_nani", name: "Nani", photo: "images/actors/nani.jpg", industry: "Tollywood" },
    { id: "actor_nagarjuna", name: "Nagarjuna", photo: "images/actors/nagarjuna.jpg", industry: "Tollywood" },
    { id: "actor_vijaydev", name: "Vijay Deverakonda", photo: "images/actors/vijay.jpg", industry: "Tollywood" },
    { id: "actor_nithin", name: "Nithin", photo: "images/actors/nithin.jpg", industry: "Tollywood" },
    { id: "actor_sharwanand", name: "Sharwanand", photo: "images/actors/sharwanand.jpg", industry: "Tollywood" },
    { id: "actor_rana", name: "Rana Daggubati", photo: "images/actors/rana.jpg", industry: "Tollywood" },
    { id: "actor_varuntej", name: "Varun Tej", photo: "images/actors/varun tej.jpg", industry: "Tollywood" },
    { id: "actor_nagachaitanya", name: "Naga Chaitanya", photo: "images/actors/nagachaitanya.jpg", industry: "Tollywood" },
    { id: "actor_siddharth", name: "Siddharth", photo: "images/actors/siddharth.jpg", industry: "Tollywood" },
    { id: "actor_vishwaksen", name: "Vishwak Sen", photo: "images/actors/vishwak sen.jpg", industry: "Tollywood" },
    { id: "actor_dulquer", name: "Dulquer Salmaan", photo: "images/actors/dulquer salmaan.jpg", industry: "Tollywood" },
    { id: "actor_kamalhaasan", name: "Kamal Haasan", photo: "images/actors/kamal haasan.jpg", industry: "Kollywood" },
    { id: "actor_leo", name: "Leonardo DiCaprio", photo: "images/actors/leo.jpg", industry: "Hollywood" },
    { id: "actor_allari", name: "Allari Naresh", photo: "images/actors/allari.jpg", industry: "Tollywood" },
    { id: "actor_aadi", name: "Aadi", photo: "images/actors/aadi.jpg", industry: "Tollywood" },
    { id: "actor_anand", name: "Anand Devarakonda", photo: "images/actors/anand.jpg", industry: "Tollywood" },
    { id: "actor_bellamkonda", name: "Bellamkonda Sai Srinivas", photo: "images/actors/bellamkonda.jpg", industry: "Tollywood" },
    { id: "actor_chaitanya", name: "Chaitanya Rao", photo: "images/actors/chaitanya.jpg", industry: "Tollywood" },
    { id: "actor_gopichand", name: "Gopichand", photo: "images/actors/gopichand.jpg", industry: "Tollywood" },
    { id: "actor_kalyanram", name: "Kalyan Ram", photo: "images/actors/kalyan ram.jpg", industry: "Tollywood" },
    { id: "actor_karthikeya", name: "Karthikeya", photo: "images/actors/karthikeya.jpg", industry: "Tollywood" },
    { id: "actor_kiccha", name: "Kiccha Sudeep", photo: "images/actors/kiccha.jpg", industry: "Sandalwood" },
    { id: "actor_manoj", name: "Manchu Manoj", photo: "images/actors/manoj.jpg", industry: "Tollywood" },
    { id: "actor_mohanlal", name: "MohanLal", photo: "images/actors/mohanlal.jpg", industry: "Mollywood" },
    { id: "actor_nandu", name: "Nandu", photo: "images/actors/nandu.jpg", industry: "Tollywood" },
    { id: "actor_nareshagastya", name: "Naresh Agastya", photo: "images/actors/naresh agastya.jpg", industry: "Tollywood" },
    { id: "actor_priyadarshi", name: "Priyadarshi", photo: "images/actors/priyadarshi.jpg", industry: "Tollywood" },
    { id: "actor_rajtarun", name: "Raj Tarun", photo: "images/actors/raj tarun.jpg", industry: "Tollywood" },
    { id: "actor_rajashekar", name: "Rajashekar", photo: "images/actors/rajashekar.jpg", industry: "Tollywood" },
    { id: "actor_rampothineni", name: "Ram Pothineni", photo: "images/actors/ram pothineni.jpg", industry: "Tollywood" },
    { id: "actor_roshankanakala", name: "Roshan Kanakala", photo: "images/actors/roshan kanakala.jpg", industry: "Tollywood" },
    { id: "actor_roshan", name: "Roshan", photo: "images/actors/roshan.jpg", industry: "Tollywood" },
    { id: "actor_saidharamtej", name: "Sai Dharam Tej", photo: "images/actors/sai dharam tej.jpg", industry: "Tollywood" },
    { id: "actor_satyadev", name: "Satyadev", photo: "images/actors/satyadev.jpg", industry: "Tollywood" },
    { id: "actor_siddu", name: "Siddu Jonnalagadda", photo: "images/actors/siddu.jpg", industry: "Tollywood" },
    { id: "actor_sreevishnu", name: "Sree Vishnu", photo: "images/actors/sree vishnu.jpg", industry: "Tollywood" },
    { id: "actor_srk", name: "Shah Rukh Khan", photo: "images/actors/srk.jpg", industry: "Bollywood" },
    { id: "actor_sudeerb", name: "Sudeer Babu", photo: "images/actors/sudeer babu.jpg", industry: "Tollywood" },
    { id: "actor_teja", name: "Teja Sajja", photo: "images/actors/teja sajja.jpg", industry: "Tollywood" },
    { id: "actor_vijaythalapathy", name: "Vijay Thalapathy", photo: "images/actors/vijay thalapathy.jpg", industry: "Kollywood" },
    // Added missing actors
    { id: "actor_ntr", name: "N. T. Rama Rao", photo: "images/actors/ntr.jpg", industry: "Tollywood" },
    { id: "actor_anr", name: "Akkineni Nageswara Rao", photo: "images/actors/anr.jpg", industry: "Tollywood" },
    { id: "actor_sumanth", name: "Sumanth", photo: "images/actors/sumanth.jpg", industry: "Tollywood" },
    { id: "actor_varunsandesh", name: "Varun Sandesh", photo: "images/actors/varun.jpg", industry: "Tollywood" },
    { id: "actor_krishnamraju", name: "Krishnam Raju", photo: "images/actors/krishnam raju.jpg", industry: "Tollywood" },
             { id: "actor_sundeepkishan", name: "Sundeep Kishan", photo: "images/actors/sundeep kishan.jpg", industry: "Tollywood" },
    { id: "actor_sonusood", name: "Sonu Sood", photo: "images/actors/sonu sood.jpg", industry: "Tollywood" },
      ],

  // ================= ACTRESSES =================
  actresses: [
    { id: "actress_rashmika", name: "Rashmika Mandanna", photo: "images/actresses/rashmika.jpg", industry: "Tollywood" },
    { id: "actress_samantha", name: "Samantha Ruth Prabhu", photo: "images/actresses/samantha.jpg", industry: "Tollywood" },
    { id: "actress_pooja", name: "Pooja Hegde", photo: "images/actresses/pooja.jpg", industry: "Tollywood" },
    { id: "actress_anushka", name: "Anushka Shetty", photo: "images/actresses/anushka.jpg", industry: "Tollywood" },
    { id: "actress_kajal", name: "Kajal Aggarwal", photo: "images/actresses/kajal.jpg", industry: "Tollywood" },
    { id: "actress_tamannah", name: "Tamannaah Bhatia", photo: "images/actresses/tamannah.jpg", industry: "Tollywood" },
    { id: "actress_sreeleela", name: "Sreeleela", photo: "images/actresses/sreeleela.jpg", industry: "Tollywood" },
    { id: "actress_keerthy", name: "Keerthy Suresh", photo: "images/actresses/keerthy.jpg", industry: "Tollywood" },
    { id: "actress_saipalavi", name: "Sai Pallavi", photo: "images/actresses/sai pallavi.jpg", industry: "Tollywood" },
    { id: "actress_nithya", name: "Nithya Menen", photo: "images/actresses/nithya.jpg", industry: "Tollywood" },
    { id: "actress_ritu", name: "Ritu Varma", photo: "images/actresses/ritu.jpg", industry: "Tollywood" },
    { id: "actress_radhika", name: "Radhika Apte", photo: "images/actresses/radhika.jpg", industry: "Tollywood" },
    { id: "actress_mrunal", name: "Mrunal Thakur", photo: "images/actresses/mrunal.jpg", industry: "Tollywood" },
    { id: "actress_genelia", name: "Genelia D'Souza", photo: "images/actresses/genelia.jpg", industry: "Tollywood" },
    { id: "actress_trisha", name: "Trisha Krishnan", photo: "images/actresses/trisha.jpg", industry: "Tollywood" },
    { id: "actress_ileana", name: "Ileana D'souza", photo: "images/actresses/ileana.jpg", industry: "Tollywood" },
    // Added missing actresses
    { id: "actress_alia", name: "Alia Bhatt", photo: "images/actresses/alia.jpg", industry: "Bollywood" },
    { id: "actress_savitri", name: "Savitri", photo: "images/actresses/savitri.jpg", industry: "Tollywood" },
    { id: "actress_suhasini", name: "Suhasini Maniratnam", photo: "images/actresses/suhasini.jpg", industry: "Tollywood" },
    { id: "actress_madhuri", name: "Madhuri Dixit", photo: "images/actresses/madhuri.jpg", industry: "Bollywood" },
    { id: "actress_saritha", name: "Saritha", photo: "images/actresses/saritha.jpg", industry: "Tollywood" },
    { id: "actress_shruti", name: "Shruti Haasan", photo: "images/actresses/shruti.jpg", industry: "Tollywood" },
    { id: "actress_shraddha", name: "Shraddha Srinath", photo: "images/actresses/shraddha.jpg", industry: "Tollywood" },
    { id: "actress_bhumika", name: "Bhumika Chawla", photo: "images/actresses/bhumika.jpg", industry: "Tollywood" },
    { id: "actress_sheela", name: "Sheela", photo: "images/actresses/sheela.jpg", industry: "Tollywood" },
    { id: "actress_kamalinee", name: "Kamalinee Mukherjee", photo: "images/actresses/kamalinee.jpg", industry: "Tollywood" },
{ id: "actress_andreajeremiah", name: "Andrea Jeremiah", photo: "images/actresses/andrea.jpg", industry: "Tollywood" },
{ id: "actress_amalapaul", name: "Amala Paul", photo: "images/actresses/amala paul.jpg", industry: "Tollywood" },
{ id: "actress_shraddhadas", name: "Shraddha Das", photo: "images/actresses/shraddha das.jpg", industry: "Tollywood" },
{ id: "actress_lakshmi", name: "Lakshmi", photo: "images/actresses/lakshmi.jpg", industry: "Tollywood" },
{ id: "actress_hansika", name: "Hansika Motwani", photo: "images/actresses/hansika.jpg", industry: "Tollywood" },
{ id: "actress_jyothika", name: "Jyothika", photo: "images/actresses/jyothika.jpg", industry: "Tollywood" },
{ id: "actress_kareenakapoor", name: "Kareena Kapoor", photo: "images/actresses/kareena kapoor.jpg", industry: "Bollywood" },
{ id: "actress_rakulpreet", name: "Rakul Preet Singh", photo: "images/actresses/rakul preet.jpg", industry: "Tollywood" },
{ id: "actress_meena", name: "Meena", photo: "images/actresses/meena.jpg", industry: "Tollywood" },
{ id: "actress_rambha", name: "Rambha", photo: "images/actresses/rambha.jpg", industry: "Tollywood" },
{ id: "actress_nagma", name: "Nagma", photo: "images/actresses/nagma.jpg", industry: "Tollywood" },
{ id: "actress_shalini", name: "Shalini Pandey", photo: "images/actresses/shalini.jpg", industry: "Tollywood" },
],

  // ================= COMEDIANS =================
  comedians: [
    { id: "comedian_brahmanandam", name: "Brahmanandam", photo: "images/comedians/brahmanandam.jpg", industry: "Tollywood" },
    { id: "comedian_ali", name: "Ali", photo: "images/comedians/ali.jpg", industry: "Tollywood" },
    { id: "comedian_msnarayana", name: "M. S. Narayana", photo: "images/comedians/ms narayana.jpg", industry: "Tollywood" },
    { id: "comedian_vennela", name: "Vennela Kishore", photo: "images/comedians/vennela.jpg", industry: "Tollywood" },
    { id: "comedian_priyadarshi", name: "Priyadarshi", photo: "images/comedians/priyadarshi.jpg", industry: "Tollywood" },
    { id: "comedian_saptagiri", name: "Saptagiri", photo: "images/comedians/saptagiri.jpg", industry: "Tollywood" },
    { id: "comedian_rahul", name: "Rahul Ramakrishna", photo: "images/comedians/rahul.jpg", industry: "Tollywood" },
    { id: "comedian_satya", name: "Satya", photo: "images/comedians/satya.jpg", industry: "Tollywood" },
    { id: "comedian_sunil", name: "Sunil", photo: "images/comedians/sunil.jpg", industry: "Tollywood" },
    { id: "comedian_rajendra", name: "Rajendra Prasad", photo: "images/comedians/rajendra.jpg", industry: "Tollywood" },
    { id: "comedian_srinivas", name: "Srinivas Reddy", photo: "images/comedians/srinivas.jpg", industry: "Tollywood" },
    // Added missing comedians
    { id: "comedian_gollapudi", name: "Gollapudi Maruti Rao", photo: "images/comedians/gollapudi.jpg", industry: "Tollywood" },
    { id: "comedian_relangi", name: "Relangi Venkata Ramaiah", photo: "images/comedians/relangi.jpg", industry: "Tollywood" }
  ],

  // ================= DIRECTORS =================
  directors: [
    { id: "dir_rajamouli", name: "S. S. Rajamouli", photo: "images/directors/rajamouli.jpg", industry: "Tollywood" },
    { id: "dir_sukumar", name: "Sukumar", photo: "images/directors/sukumar.jpg", industry: "Tollywood" },
    { id: "dir_trivikram", name: "Trivikram Srinivas", photo: "images/directors/trivikram.jpg", industry: "Tollywood" },
    { id: "dir_koratala", name: "Koratala Siva", photo: "images/directors/koratala.jpg", industry: "Tollywood" },
    { id: "dir_vamshi", name: "Vamshi Paidipally", photo: "images/directors/vamshi.jpg", industry: "Tollywood" },
    { id: "dir_anil", name: "Anil Ravipudi", photo: "images/directors/anil.jpg", industry: "Tollywood" },
    { id: "dir_puri", name: "Puri Jagannadh", photo: "images/directors/puri.jpg", industry: "Tollywood" },
    { id: "dir_sekhar", name: "Sekhar Kammula", photo: "images/directors/sekhar.jpg", industry: "Tollywood" },
    { id: "dir_prasanth", name: "Prasanth Varma", photo: "images/directors/prasanthvarma.jpg", industry: "Tollywood" },
    { id: "dir_nag", name: "Nag Ashwin", photo: "images/directors/nagaashwin.jpg", industry: "Tollywood" },
    { id: "dir_boyapati", name: "Boyapati Srinu", photo: "images/directors/boyapati.jpg", industry: "Tollywood" },
    { id: "dir_srinu", name: "Srinu Vaitla", photo: "images/directors/srinu.jpg", industry: "Tollywood" },
    { id: "dir_viswanath", name: "K. Viswanath", photo: "images/directors/viswanath.jpg", industry: "Tollywood" }
   ],

  // ================= MOVIES =================
  movies: [
    {
      id: 1,
      title: "RRR",
      year: 2022,
      genre: "Action • Drama • Period",
      industry: "Tollywood",
      poster: "images/movies/rrr.jpg",
      description: "A fictional tale of two legendary revolutionaries and their journey away from home before they started fighting for their country in the 1920s.",
      trailer: "https://www.youtube.com/watch?v=GY4CDmUY7vA",
      directorId: "dir_rajamouli",
      actorIds: ["actor_jrntr", "actor_ramcharan", "actor_rana"],
      actressIds: ["actress_alia"],
      comedianIds: []
    },
    {
      id: 2,
      title: "Pushpa: The Rise",
      year: 2021,
      genre: "Action • Drama",
      industry: "Tollywood",
      poster: "images/movies/pushpa 1.jpg",
      description: "Violence erupts between red sandalwood smugglers and the police charged with bringing down their organization.",
      trailer: "https://www.youtube.com/watch?v=pKctjlxbFDQ",
      directorId: "dir_sukumar",
      actorIds: ["actor_alluarjun"],
      actressIds: ["actress_rashmika"],
      comedianIds: ["comedian_sunil"]
    },
    {
      id: 3,
      title: "Baahubali 2: The Conclusion",
      year: 2017,
      genre: "Action • Drama • Fantasy",
      industry: "Tollywood",
      poster: "images/movies/baahubali 2.jpg",
      description: "When Shiva, the son of Bahubali, learns about his heritage, he begins to look for answers. His story is juxtaposed with past events that unfolded in the Mahishmati Kingdom.",
      trailer: "https://www.youtube.com/watch?v=G62HrubdD6o",
      directorId: "dir_rajamouli",
       actorIds: ["actor_prabhas", "actor_rana"],
  actressIds: ["actress_anushka", "actress_tamannah"],
  comedianIds: []
},
{
  id: 4,
  title: "Ala Vaikunthapurramuloo",
  year: 2020,
  genre: "Action • Drama • Family",
  industry: "Tollywood",
  poster: "images/movies/avpl.jpg",
  description: "After growing up enduring criticism from his father, a young man finds his world shaken upon learning he was switched at birth with a millionaire's son.",
  trailer: "https://www.youtube.com/watch?v=dhQT4me2dUs",
  directorId: "dir_trivikram",
  actorIds: ["actor_alluarjun"],
  actressIds: ["actress_pooja"],
  comedianIds: ["comedian_rahul", "comedian_vennela"]
},
{
  id: 5,
  title: "Srimanthudu",
  year: 2015,
  genre: "Action • Drama",
  industry: "Tollywood",
  poster: "images/movies/srimanthudu.jpg",
  description: "Harsha, a multi-millionaire who has everything, still feels that there is something missing in his life. In an attempt to fill the void, he adopts a village.",
  trailer: "https://www.youtube.com/watch?v=m7XeMyInWsE",
  directorId: "dir_koratala",
  actorIds: ["actor_maheshbabu"],
  actressIds: ["actress_shruti"],
  comedianIds: []
},
{
  id: 6,
  title: "Rangasthalam",
  year: 2018,
  genre: "Action • Drama • Period",
  industry: "Tollywood",
  poster: "images/movies/rangasthalam.jpg",
  description: "The fear of his elder brother's death starts to haunt an innocent, hearing impaired guy after they both join forces to overthrow the unlawful 30 year long regime of their village's president.",
  trailer: "https://www.youtube.com/watch?v=vRbZJEhbKsw",
  directorId: "dir_sukumar",
  actorIds: ["actor_ramcharan"],
  actressIds: ["actress_samantha"],
  comedianIds: []
},
{
  id: 7,
  title: "Jersey",
  year: 2019,
  genre: "Sports • Drama",
  industry: "Tollywood",
  poster: "images/movies/jersey.jpg",
  description: "A failed cricketer decides to revive his cricketing career in his late 30s despite everyone being skeptical of his ability to do so.",
  trailer: "https://www.youtube.com/watch?v=_IO_k1nRB2U",
  directorId: "dir_gowtam",
  actorIds: ["actor_nani"],
  actressIds: ["actress_shraddha"],
  comedianIds: []
},
{
  id: 8,
  title: "Sita Ramam",
  year: 2022,
  genre: "Romance • Drama • Period",
  industry: "Tollywood",
  poster: "images/movies/sita ramam.jpg",
  description: "An orphan soldier, Lieutenant Ram's life changes after he receives a letter from a girl named Sita. He meets her and love blossoms between them.",
  trailer: "https://www.youtube.com/watch?v=WzuB7p65qWU",
  directorId: "dir_hanu",
  actorIds: ["actor_dulquer"],
  actressIds: ["actress_mrunal"],
  comedianIds: []
},
{
  id: 9,
  title: "Pelli Choopulu",
  year: 2016,
  genre: "Romance • Comedy",
  industry: "Tollywood",
  poster: "images/movies/pelli choopulu.jpg",
  description: "Two people are forced to go on a blind date by their parents, but they don't get along at all. However, they soon find themselves in a business partnership.",
  trailer: "https://www.youtube.com/watch?v=J80XO3v1tXs",
  directorId: "dir_tharun",
  actorIds: ["actor_vijaydev"],
  actressIds: ["actress_ritu"],
  comedianIds: ["comedian_priyadarshi"]
},
{
  id: 10,
  title: "Bommarillu",
  year: 2006,
  genre: "Romance • Drama • Family",
  industry: "Tollywood",
  poster: "images/movies/bommarillu.jpg",
  description: "A young man realizes that he has to push back against his domineering father if he wants to find true happiness and love.",
  trailer: "https://www.youtube.com/watch?v=qlAjkWnJmUo",
  directorId: "dir_bhaskar",
  actorIds: ["actor_siddharth"],
  actressIds: ["actress_genelia"],
  comedianIds: []
},
{
  id: 11,
  title: "Athadu",
  year: 2005,
  genre: "Action • Thriller",
  industry: "Tollywood",
  poster: "images/movies/athadu.jpg",
  description: "A gunman for hire is framed for murder, and assumes a dead man's identity while hiding from the police.",
  trailer: "https://www.youtube.com/watch?v=ZB-iA-wT5CU",
  directorId: "dir_trivikram",
  actorIds: ["actor_maheshbabu"],
  actressIds: ["actress_trisha"],
  comedianIds: ["comedian_brahmanandam"]
},
{
  id: 12,
  title: "Mahanati",
  year: 2018,
  genre: "Biography • Drama",
  industry: "Tollywood",
  poster: "images/movies/mahanati.jpg",
  description: "Biography of Savitri, an actress from South India movie industry, who ruled the industry for two decades during 50s and 60s.",
  trailer: "https://www.youtube.com/watch?v=5MqSNjoCTbo",
  directorId: "dir_nag",
  actorIds: ["actor_dulquer", "actor_vijaydev"],
  actressIds: ["actress_keerthy", "actress_samantha"],
  comedianIds: []
},
{
  id: 13,
  title: "HanuMan",
  year: 2024,
  genre: "Action • Fantasy • Superhero",
  industry: "Tollywood",
  poster: "images/movies/hanuman.jpg",
  description: "An imaginary place called Anjanadri where the protagonist gets the powers of Hanuman and fights for Anjanadri.",
  trailer: "https://www.youtube.com/watch?v=BNHZq8OcvJo",
  directorId: "dir_prasanth",
  actorIds: ["actor_teja"],
  actressIds: ["actress_amritha"],
  comedianIds: ["comedian_vennela"]
},
{
  id: 14,
  title: "Arjun Reddy",
  year: 2017,
  genre: "Romance • Drama",
  industry: "Tollywood",
  poster: "images/movies/arjun reddy.jpg",
  description: "Arjun Reddy, a short-tempered house surgeon, gets used to drugs and drinks when his girlfriend is forced to marry another person.",
  trailer: "https://www.youtube.com/watch?v=hmXeO8DGgpo",
  directorId: "dir_sandeep",
  actorIds: ["actor_vijaydev"],
  actressIds: ["actress_shalini"],
  comedianIds: []
},
{
  id: 15,
  title: "Eega",
  year: 2012,
  genre: "Fantasy • Thriller • Romance",
  industry: "Tollywood",
  poster: "images/movies/eega.jpg",
  description: "Nani loves Bindu but is killed by a jealous Sudeep, who lusts after Bindu. Nani is reincarnated as a fly and decides to avenge his death.",
  trailer: "https://www.youtube.com/watch?v=vDv7Fwk6ulY",
  directorId: "dir_rajamouli",
  actorIds: ["actor_nani", "actor_sudeepkishan"],
  actressIds: ["actress_samantha"],
  comedianIds: []
},
{
  id: 16,
  title: "Pokiri",
  year: 2006,
  genre: "Action • Crime • Thriller",
  industry: "Tollywood",
  poster: "images/movies/pokiri.jpg",
  description: "A local goon's killer instincts earn him his girlfriend's disapproval. Meanwhile, a cop looks for a pattern in a string of murders.",
  trailer: "https://www.youtube.com/watch?v=HJhNWGzC7tI",
  directorId: "dir_puri",
  actorIds: ["actor_maheshbabu"],
  actressIds: ["actress_ileana"],
  comedianIds: ["comedian_brahmanandam", "comedian_ali"]
},
{
  id: 17,
  title: "Magadheera",
  year: 2009,
  genre: "Action • Fantasy • Romance",
  industry: "Tollywood",
  poster: "images/movies/magadheera.jpg",
  description: "A warrior gets reincarnated 400 years later, after trying to save the princess and the kingdom, who also dies along with him. He then sets back to fight against all odds and win back his love.",
  trailer: "https://www.youtube.com/watch?v=wfWkmURBNv8",
  directorId: "dir_rajamouli",
  actorIds: ["actor_ramcharan"],
  actressIds: ["actress_kajal"],
  comedianIds: []
},
{
  id: 18,
  title: "Fidaa",
  year: 2017,
  genre: "Romance • Drama",
  industry: "Tollywood",
  poster: "images/movies/fidaa.jpg",
  description: "Varun and Bhanu, both from different worlds, face challenges in convincing their families about their love for each other.",
  trailer: "https://www.youtube.com/watch?v=bMVLhL_lZrU",
  directorId: "dir_sekhar",
  actorIds: ["actor_varuntej"],
  actressIds: ["actress_saipalavi"],
  comedianIds: []
},
{
  id: 19,
  title: "Vedam",
  year: 2010,
  genre: "Drama • Action",
  industry: "Tollywood",
  poster: "images/movies/vedam.jpg",
  description: "Five people from varied strata of society – a slum dweller who works as a cable operator, a runaway prostitute, a desperate woman drowning in debt, a rising musician, and a grief-stricken Muslim man – end up together in the same hospital.",
  trailer: "https://www.youtube.com/watch?v=v5AuNL8e1mQ",
  directorId: "dir_krish",
  actorIds: ["actor_alluarjun"],
  actressIds: ["actress_anushka"],
  comedianIds: []
},
{
  id: 20,
  title: "Mayabazar",
  year: 1957,
  genre: "Fantasy • Drama • Musical",
  industry: "Tollywood",
  poster: "images/movies/mayabazar.jpg",
  description: "Balarama promises to get his daughter married to Abhimanyu, but on the day of the wedding, Abhimanyu is killed and the wedding is cancelled. So Krishna and Ghatotkacha plan to set things right.",
  trailer: "https://www.youtube.com/watch?v=l0k0yVn9mKo",
  directorId: "dir_kvreddy",
  actorIds: ["actor_ntr", "actor_anr"],
  actressIds: ["actress_savitri"],
  comedianIds: ["comedian_relangi"]
},
{
  id: 21,
  title: "Okkadu",
  year: 2003,
  genre: "Action • Romance • Drama",
  industry: "Tollywood",
  poster: "images/movies/okkadu.jpg",
  description: "Ajay, a carefree young man, falls in love with Swapna, but their relationship faces challenges when he discovers her past and his own identity.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_bobbykolli",
  actorIds: ["actor_maheshbabu"],
  actressIds: ["actress_bhumika"],
  comedianIds: []
},
{
  id: 22,
  title: "Oh My Friend",
  year: 2011,
  genre: "Drama • Romance",
  industry: "Tollywood",
  poster: "images/movies/ohmyfriend.jpg",
  description: "Chandu, a carefree guy, and Siri, a disciplined girl, become friends, but their bond is tested by life's challenges and personal struggles.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_vinayak",
  actorIds: ["actor_siddharth"],
  actressIds: ["actress_shrutihaasan"],
  comedianIds: []
},
{
  id: 23,
  title: "Koncham Istam Koncham Kastam",
  year: 2009,
  genre: "Romance • Comedy",
  industry: "Tollywood",
  poster: "images/movies/konchamistamkonchamkastam.jpg",
  description: "Geetha, a modern girl, and Arjun, a traditional guy, fall in love, but their differing lifestyles create humorous and emotional conflicts.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_kishore",
  actorIds: ["actor_siddharth"],
  actressIds: ["actress_tamannaah"],
  comedianIds: []
},
{
  id: 24,
  title: "Nuvvostanante Nenoddantana",
  year: 2005,
  genre: "Romance • Drama",
  industry: "Tollywood",
  poster: "images/movies/nuvvostanantenenoddantana.jpg",
  description: "Siddhu, a carefree guy, and Siri, a disciplined girl, develop a friendship that blossoms into love, facing family and societal pressures.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_prabhudeva",
  actorIds: ["actor_siddharth"],
  actressIds: ["actress_trisha"],
  comedianIds: []
},
{
  id: 25,
  title: "Rachcha",
  year: 2012,
  genre: "Action • Romance",
  industry: "Tollywood",
  poster: "images/movies/rachcha.jpg",
  description: "Betting Raja, a gambler, falls in love with Radha, but his past debts and enemies threaten their relationship.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_sampathnandi",
  actorIds: ["actor_ramcharan"],
  actressIds: ["actress_tamannaah"],
  comedianIds: []
},
{
  id: 26,
  title: "Ala Modalaindi",
  year: 2011,
  genre: "Comedy • Romance",
  industry: "Tollywood",
  poster: "images/movies/alamodalaindi.jpg",
  description: "Gauthami and Ravindra pretend to be a couple to win a competition, leading to real feelings.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_mohanraja",
  actorIds: ["actor_nani"],
  actressIds: ["actress_nithya"],
  comedianIds: []
},
{
  id: 27,
  title: "Pournami",
  year: 2006,
  genre: "Horror • Thriller",
  industry: "Tollywood",
  poster: "images/movies/pournami.jpg",
  description: "A couple moves into a haunted house, uncovering dark secrets and supernatural forces.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_prakashraj",
  actorIds: ["actor_prakashraj"],
  actressIds: ["actress_lakshmi"],
  comedianIds: []
},
{
  id: 28,
  title: "Brindavanam",
  year: 2010,
  genre: "Action • Drama",
  industry: "Tollywood",
  poster: "images/movies/brindavanam.jpg",
  description: "Krishna fights against corruption and injustice to protect his love and family.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_vamshi",
  actorIds: ["actor_krishnamraju"],
  actressIds: ["actress_kajal"],
  comedianIds: []
},
{
  id: 29,
  title: "Orange",
  year: 2010,
  genre: "Romance • Drama",
  industry: "Tollywood",
  poster: "images/movies/orange.jpg",
  description: "Ram and Jaanu fall in love, but their relationship is challenged by expectations and growth.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_bharath",
  actorIds: ["actor_ramcharan"],
  actressIds: ["actress_genelia"],
  comedianIds: []
},
{
  id: 30,
  title: "Businessman",
  year: 2012,
  genre: "Action • Drama",
  industry: "Tollywood",
  poster: "images/movies/businessman.jpg",
  description: "A powerful businessman fights against a corrupt politician to protect his empire.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_puri",
  actorIds: ["actor_maheshbabu"],
  actressIds: ["actress_kajal"],
  comedianIds: []
},
{
  id: 31,
  title: "Siddu from Srikakulam",
  year: 2008,
  genre: "Comedy • Romance",
  industry: "Tollywood",
  poster: "images/movies/siddufromsrikakulam.jpg",
  description: "Siddu moves from a village to the city and falls in love with Anjali while navigating funny and emotional situations.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_ravi",
  actorIds: ["actor_allariramudu"],
  actressIds: ["actress_genelia"],
  comedianIds: []
},
{
  id: 32,
  title: "Arya 2",
  year: 2009,
  genre: "Action • Romance",
  industry: "Tollywood",
  poster: "images/movies/arya 2.jpg",
  description: "Arya’s intense love for Geetha creates chaos when obsession and friendship collide.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
    directorId: "dir_sukumar",
  actorIds: ["actor_alluarjun"],
  actressIds: ["actress_kajal"],
  comedianIds: []
},
{
  id: 33,
  title: "Chukkalo Chandrudu",
  year: 2006,
  genre: "Comedy • Romance",
  industry: "Tollywood",
  poster: "images/movies/chukkalochandrudu.jpg",
  description: "Chandru’s love life turns complicated as he gets involved with multiple women.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_siddhu",
  actorIds: ["actor_siddharth"],
  actressIds: ["actress_sadhana"],
  comedianIds: []
},
{
  id: 34,
  title: "Maska",
  year: 2009,
  genre: "Action • Drama",
  industry: "Tollywood",
  poster: "images/movies/maska.jpg",
  description: "A clever conman pretends to be rich, leading to unexpected love and danger.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_bakkiyaraj",
  actorIds: ["actor_ramcharan"],
  actressIds: ["actress_hansika"],
  comedianIds: []
},
{
  id: 35,
  title: "Kandireega",
  year: 2011,
  genre: "Action • Comedy",
  industry: "Tollywood",
  poster: "images/movies/kandireega.jpg",
  description: "A carefree young man enters a village feud and wins hearts with humor and courage.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_santoshsrinivas",
  actorIds: ["actor_ram"],
  actressIds: ["actress_hansika"],
  comedianIds: []
},
{
  id: 36,
  title: "Parugu",
  year: 2008,
  genre: "Action • Drama",
  industry: "Tollywood",
  poster: "images/movies/parugu.jpg",
  description: "A man helps lovers escape against family opposition and discovers love himself.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_bhaskar",
  actorIds: ["actor_alluarjun"],
  actressIds: ["actress_sheela"],
  comedianIds: []
},
{
  id: 37,
  title: "Varsham",
  year: 2004,
  genre: "Romance • Drama",
  industry: "Tollywood",
  poster: "images/movies/varsham.jpg",
  description: "A couple’s love story unfolds amidst rain, rivalry, and emotional turmoil.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_mohanraja",
  actorIds: ["actor_prabhas"],
  actressIds: ["actress_trisha"],
  comedianIds: []
},
{
  id: 38,
  title: "Adhurs",
  year: 2010,
  genre: "Action • Comedy",
  industry: "Tollywood",
  poster: "images/movies/adhurs.jpg",
  description: "Twin brothers—one innocent, one mischievous—create chaos and comedy.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_vetri",
  actorIds: ["actor_ntr"],
  actressIds: ["actress_shayami"],
  comedianIds: []
},
{
  id: 39,
  title: "Super",
  year: 2005,
  genre: "Action • Comedy",
  industry: "Tollywood",
  poster: "images/movies/super.jpg",
  description: "A cheerful man rises against villains and corruption with style and humor.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_puri",
  actorIds: ["actor_sumanth"],
  actressIds: ["actress_genelia"],
  comedianIds: []
},
{
  id: 40,
  title: "Godavari",
  year: 2006,
  genre: "Romance • Drama",
  industry: "Tollywood",
  poster: "images/movies/godavari.jpg",
  description: "A boat journey becomes a journey of love, emotions, and self-discovery.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_srinu",
  actorIds: ["actor_sumanth"],
  actressIds: ["actress_kamalinee"],
  comedianIds: []
},
{
  id: 41,
  title: "Happy Days",
  year: 2007,
  genre: "Romance • Comedy",
  industry: "Tollywood",
  poster: "images/movies/happydays.jpg",
  description: "Engineering students experience friendship, love, and heartbreak.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_sekar",
  actorIds: ["actor_varunsandesh"],
  actressIds: ["actress_tamannaah"],
  comedianIds: []
},
{
  id: 42,
  title: "Khaleja",
  year: 2010,
  genre: "Action • Fantasy",
  industry: "Tollywood",
  poster: "images/movies/khaleja.jpg",
  description: "A taxi driver becomes a savior while battling fate and powerful enemies.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_trivikram",
  actorIds: ["actor_maheshbabu"],
  actressIds: ["actress_anushka"],
  comedianIds: []
},
{
  id: 43,
  title: "Rechipo",
  year: 2009,
  genre: "Action • Romance",
  industry: "Tollywood",
  poster: "images/movies/rechipo.jpg",
  description: "A boxer’s past returns to threaten his love and future.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_raghubabu",
  actorIds: ["actor_ramcharan"],
  actressIds: ["actress_tamannaah"],
  comedianIds: []
},
{
  id: 44,
  title: "Dookudu",
  year: 2011,
  genre: "Action • Comedy",
  industry: "Tollywood",
  poster: "images/movies/dookudu.jpg",
  description: "An undercover cop takes on a dangerous political family with wit and power.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_srinu",
  actorIds: ["actor_maheshbabu"],
  actressIds: ["actress_samantha"],
  comedianIds: []
},
{
  id: 45,
  title: "Ganesh",
  year: 2009,
  genre: "Action • Drama",
  industry: "Tollywood",
  poster: "images/movies/ganesh.jpg",
  description: "A common man rises against injustice to protect his family.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_suresh",
  actorIds: ["actor_ram"],
  actressIds: ["actress_kajal"],
  comedianIds: []
},
{
  id: 46,
  title: "Badrinath",
  year: 2011,
  genre: "Action • Romance",
  industry: "Tollywood",
  poster: "images/movies/badrinath.jpg",
  description: "A warrior sworn to peace is forced into battle for love.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_vvvinayak",
  actorIds: ["actor_alluarjun"],
  actressIds: ["actress_tamannaah"],
  comedianIds: []
},
{
  id: 47,
  title: "Ishq",
  year: 2012,
  genre: "Romance • Drama",
  industry: "Tollywood",
  poster: "images/movies/ishq.jpg",
  description: "Two lovers struggle against ego, misunderstandings, and family pride.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_vikram",
  actorIds: ["actor_nani"],
  actressIds: ["actress_shraddhadas"],
  comedianIds: []
},
{
  id: 48,
  title: "Nenu Naa Rakshasi",
  year: 2011,
  genre: "Action • Thriller",
  industry: "Tollywood",
  poster: "images/movies/nenunaarakshasi.jpg",
  description: "The journey of a girl who is interested in suicides and a boy who is interested in her.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_pavan",
  actorIds: ["actor_vishnumanchu", "actor_sundeepkishan"],
  actressIds: [],
  comedianIds: []
},
{
  id: 49,
  title: "Arundhati",
  year: 2009,
  genre: "Horror • Thriller",
  industry: "Tollywood",
  poster: "images/movies/arundhati.jpg",
  description: "A woman confronts her terrifying past life to defeat evil forces.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_kodi",
  actorIds: ["actor_sonusood"],
  actressIds: ["actress_anushka"],
  comedianIds: []
},
{
  id: 50,
  title: "Ashta Chamma",
  year: 2008,
  genre: "Action • Drama",
  industry: "Tollywood",
  poster: "images/movies/ashta chamma.jpg",
  description: "Siddhu fights against a corrupt system and powerful enemies to protect his family and love.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_suresh",
  actorIds: ["actor_nani"],
  actressIds: ["actress_genelia"],
  comedianIds: []
},
{
  id: 51,
  title: "Pilla Zamindar",
  year: 2011,
  genre: "Action • Comedy",
  industry: "Tollywood",
  poster: "images/movies/pilla zamindar.jpg",
  description: "A spoiled heir is forced to live like a common man and learns the true meaning of life and love.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_asokan",
  actorIds: ["actor_nani"],
  actressIds: ["actress_andreajeremiah"],
  comedianIds: []
},
{
  id: 52,
  title: "Julayi",
  year: 2012,
  genre: "Action • Comedy",
  industry: "Tollywood",
  poster: "images/movies/julayi.jpg",
  description: "A clever man locks horns with a powerful criminal in a high-stakes battle of brains and brawn.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_trivikram",
  actorIds: ["actor_alluarjun"],
  actressIds: ["actress_ileana"],
  comedianIds: []
},
{
  id: 53,
  title: "Pushpa: The Rule",
  year: 2024,
  genre: "Action • Drama",
  industry: "Tollywood",
  poster: "images/movies/pushpa 2.jpg",
  description: "Pushpa Raj rises through the ranks of the red sandalwood smuggling syndicate, becoming a powerful force.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_sukumar",
  actorIds: ["actor_alluarjun"],
  actressIds: ["actress_rashmikamandanna"],
  comedianIds: []
},
{
  id: 54,
  title: "Sarrainodu",
  year: 2016,
  genre: "Action • Thriller",
  industry: "Tollywood",
  poster: "images/movies/sarrainodu.jpg",
  description: "A fearless man takes on a corrupt politician in a brutal battle for justice.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_boyapatisrinu",
  actorIds: ["actor_alluarjun"],
  actressIds: ["actress_rakulpreet"],
  comedianIds: []
},
{
  id: 55,
  title: "Naa Peru Surya, Naa Illu India",
  year: 2018,
  genre: "Action • Comedy",
  industry: "Tollywood",
  poster: "images/movies/npsnii.jpg",
  description: "A short-tempered soldier embarks on a journey of self-control and redemption.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_vakkanthamvamsi",
  actorIds: ["actor_alluarjun"],
  actressIds: ["actress_anveshijain"],
  comedianIds: []
},
{
  id: 56,
  title: "DJ",
  year: 2006,
  genre: "Action • Romance",
  industry: "Tollywood",
  poster: "images/movies/dj.jpg",
  description: "A disc jockey gets caught in a dangerous political conspiracy while fighting for justice.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_karthiksabu",
  actorIds: ["actor_alluarjun"],
  actressIds: ["actress_pooja"],
  comedianIds: []
},
{
  id: 57,
  title: "Aarya 1",
  year: 2004,
  genre: "Romance • Drama",
  industry: "Tollywood",
  poster: "images/movies/aarya 1.jpg",
  description: "Arya’s unconditional love challenges society, friendship, and fate.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_balasekaran",
  actorIds: ["actor_alluarjun"],
  actressIds: ["actress_anushkashetty"],
  comedianIds: []
},
{
  id: 58,
  title: "Race Gurram",
  year: 2014,
  genre: "Action • Comedy",
  industry: "Tollywood",
  poster: "images/movies/race gurram.jpg",
  description: "Two brothers with opposite personalities unite to defeat a ruthless villain.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_surenderreddy",
  actorIds: ["actor_alluarjun"],
  actressIds: ["actress_sruthi"],
  comedianIds: []
},
{
  id: 59,
  title: "Happy",
  year: 2006,
  genre: "Action • Romance",
  industry: "Tollywood",
  poster: "images/movies/happy.jpg",
  description: "A carefree youth changes himself for love and family acceptance.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_akarunakaran",
  actorIds: ["actor_alluarjun"],
  actressIds: ["actress_genelia"],
  comedianIds: []
},
{
  id: 60,
  title: "S/O Satyamurthy",
  year: 2015,
  genre: "Comedy • Drama",
  industry: "Tollywood",
  poster: "images/movies/sonof.jpg",
  description: "A man tries to uphold his father’s values while navigating love and responsibility.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_trivikram",
  actorIds: ["actor_alluarjun"],
  actressIds: ["actress_samantha"],
  comedianIds: []
},
{
  id: 61,
  title: "Iddarammayilatho",
  year: 2013,
  genre: "Action • Romance",
  industry: "Tollywood",
  poster: "images/movies/iddarammayilatho.jpg",
  description: "A guitarist’s love story turns dark as revenge and betrayal surface.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_puri",
  actorIds: ["actor_alluarjun"],
  actressIds: ["actress_amalapaul"],
  comedianIds: []
},
{
  id: 62,
  title: "Desamuduru",
  year: 2007,
  genre: "Action • Drama",
  industry: "Tollywood",
  poster: "images/movies/desamuduru.jpg",
  description: "A fearless reporter falls in love while battling criminals and corruption.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_puri",
  actorIds: ["actor_prabhas"],
  actressIds: ["actress_hansika"],
  comedianIds: []
},
{
  id: 63,
  title: "Bunny",
  year: 2005,
  genre: "Action • Thriller",
  industry: "Tollywood",
  poster: "images/movies/bunny.jpg",
  description: "A clever young man infiltrates a crime empire to protect his family.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_vvvinayak",
  actorIds: ["actor_alluarjun"],
  actressIds: ["actress_madhuri"],
  comedianIds: []
},
{
  id: 64,
  title: "Varudu",
  year: 2010,
  genre: "Action • Romance",
  industry: "Tollywood",
  poster: "images/movies/varudu.jpg",
  description: "A man returns to India for an arranged marriage that spirals into violence.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_gunasekhar",
  actorIds: ["actor_alluarjun"],
  actressIds: ["actress_hansika"],
  comedianIds: []
},
{
  id: 65,
  title: "Rudhramadevi",
  year: 2015,
  genre: "Action • Historical",
  industry: "Tollywood",
  poster: "images/movies/rudhramadevi.jpg",
  description: "The epic tale of Queen Rudramadevi, who rules and defends her kingdom in disguise.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_gunasekhar",
  actorIds: ["actor_alluarjun", "actor_rana"],
  actressIds: ["actress_anushkashetty"],
  comedianIds: []
},
{
  id: 66,
  title: "Gangotri",
  year: 2003,
  genre: "Action • Romance",
  industry: "Tollywood",
    poster: "images/movies/gangotri.jpg",
  description: "A village youth experiences first love while facing rigid traditions.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_kvijayabhaskar",
  actorIds: ["actor_alluarjun"],
  actressIds: ["actress_aditirao"],
  comedianIds: []
},
{
  id: 67,
  title: "Yevadu",
  year: 2010,
  genre: "Action • Thriller",
  industry: "Tollywood",
  poster: "images/movies/yevadu.jpg",
  description: "A man with a hidden past seeks revenge against those who betrayed him.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_bobbykolli",
  actorIds: ["actor_alluarjun", "actor_ramcharan"],
  actressIds: ["actress_kajal"],
  comedianIds: []
},
{
  id: 68,
  title: "Punadhirallu",
  year: 1978,
  genre: "Action • Drama",
  industry: "Tollywood",
  poster: "images/movies/punadhirallu.jpg",
  description: "A young man embarks on a quest for revenge against those who destroyed his family, facing various challenges along the way.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_rajendrasinghbabu",
  actorIds: ["actor_chiranjeevi"],
  actressIds: ["actress_suhasini"],
  comedianIds: []
},
{
  id: 69,
  title: "Mana Voori Pandavulu",
  year: 1978,
  genre: "Drama",
  industry: "Tollywood",
  poster: "images/movies/manavoori_pandavulu.jpg",
  description: "A modern retelling of the Pandavas story, focusing on themes of justice and family bonds in a rural setting.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_bapu",
  actorIds: ["actor_chiranjeevi"],
  actressIds: ["actress_suhasini"],
  comedianIds: []
},
{
  id: 70,
  title: "Pranam Khareedu",
  year: 1978,
  genre: "Action • Drama",
  industry: "Tollywood",
  poster: "images/movies/pranam_khareedu.jpg",
  description: "A story of a man who fights against corruption and injustice in his village, inspired by real events.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_kvasu",
  actorIds: ["actor_chiranjeevi"],
  actressIds: ["actress_madhuri"],
  comedianIds: []
},
{
  id: 71,
  title: "Andharivadu",
  year: 1978,
  genre: "Action • Drama",
  industry: "Tollywood",
  poster: "images/movies/andharivadu.jpg",
  description: "A young man disguises himself to uncover the truth behind his father's death and bring the culprits to justice.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_sraja",
  actorIds: ["actor_chiranjeevi"],
  actressIds: ["actress_saritha"],
  comedianIds: []
},
{
  id: 72,
  title: "Manavoori Pandavulu",
  year: 1978,
  genre: "Drama",
  industry: "Tollywood",
  poster: "images/movies/manavoori_pandavulu.jpg",
  description: "A tale of five brothers who face hardships and unite to overcome evil forces in their community.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_balumahendra",
  actorIds: ["actor_chiranjeevi"],
  actressIds: ["actress_suhasini"],
  comedianIds: []
},
{
  id: 74,
  title: "Tayaramma Bangarayya",
  year: 1979,
  genre: "Comedy • Drama",
  industry: "Tollywood",
  poster: "images/movies/tayaramma_bangarayya.jpg",
  description: "A humorous take on a couple's marital life and their adventures in a village setting.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_kvasu",
  actorIds: ["actor_chiranjeevi"],
  actressIds: ["actress_saritha"],
  comedianIds: ["comedian_gollapudi"]
},
{
  id: 75,
  title: "Kukka Katuku Cheppu Debba",
  year: 1979,
  genre: "Comedy",
  industry: "Tollywood",
  poster: "images/movies/kukka_katuku_cheppu_debba.jpg",
  description: "A light-hearted comedy about a man who gets involved in funny situations while trying to impress his love interest.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_kvasu",
  actorIds: ["actor_chiranjeevi"],
  actressIds: ["actress_madhuri"],
  comedianIds: ["comedian_gollapudi"]
},
{
  id: 76,
  title: "Kotta Alludu",
  year: 1979,
  genre: "Action • Drama",
  industry: "Tollywood",
  poster: "images/movies/kotta_alludu.jpg",
  description: "A young man fights against a corrupt landlord to protect his village and loved ones.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_kvasu",
  actorIds: ["actor_chiranjeevi"],
  actressIds: ["actress_saritha"],
  comedianIds: []
},
{
  id: 77,
  title: "I Love You",
  year: 1979,
  genre: "Romance • Drama",
  industry: "Tollywood",
  poster: "images/movies/i_love_you.jpg",
  description: "A romantic story of a young couple navigating love, family expectations, and societal pressures.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_kvasu",
  actorIds: ["actor_chiranjeevi"],
  actressIds: ["actress_madhuri"],
  comedianIds: []
},
{
  id: 78,
  title: "Idi Katha Kaadu",
  year: 1979,
  genre: "Action • Drama",
  industry: "Tollywood",
  poster: "images/movies/idi_katha_kaadu.jpg",
  description: "A man seeks justice for his sister's death by taking on powerful adversaries in a tale of revenge and righteousness.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_kvasu",
  actorIds: ["actor_chiranjeevi"],
  actressIds: ["actress_saritha"],
  comedianIds: []
},
{
  id: 79,
  title: "Sri Rambantu",
  year: 1979,
  genre: "Comedy • Drama",
  industry: "Tollywood",
  poster: "images/movies/sri_rambantu.jpg",
  description: "A comedic story about a man who pretends to be a saint to resolve family issues and village problems.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_kvasu",
  actorIds: ["actor_chiranjeevi"],
  actressIds: ["actress_madhuri"],
  comedianIds: ["comedian_gollapudi"]
},
{
  id: 80,
  title: "Kothala Raayudu",
  year: 1979,
  genre: "Action • Drama",
  industry: "Tollywood",
  poster: "images/movies/kothala_raayudu.jpg",
  description: "A brave man battles a tyrannical ruler to free his people from oppression and injustice.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_kvasu",
  actorIds: ["actor_chiranjeevi"],
  actressIds: ["actress_saritha"],
  comedianIds: []
},
{
  id: 81,
  title: "Mosagadu",
  year: 1980,
  genre: "Action • Drama",
  industry: "Tollywood",
  poster: "images/movies/mosagadu.jpg",
  description: "A thief turns into a hero to protect a village from a gang of criminals and falls in love along the way.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_kvasu",
  actorIds: ["actor_chiranjeevi"],
  actressIds: ["actress_saritha"],
  comedianIds: []
},
{
  id: 82,
  title: "Nakili Manishi",
  year: 1980,
  genre: "Action • Drama",
  industry: "Tollywood",
  poster: "images/movies/nakili_manishi.jpg",
  description: "A man uses disguises to fight crime and bring down a corrupt system in his town.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_kvasu",
  actorIds: ["actor_chiranjeevi"],
  actressIds: ["actress_madhuri"],
  comedianIds: []
},
{
  id: 83,
  title: "Kaali",
  year: 1980,
  genre: "Action • Drama",
  industry: "Tollywood",
  poster: "images/movies/kaali.jpg",
  description: "A fierce warrior fights against evil forces to avenge his family's death and restore peace.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_kvasu",
  actorIds: ["actor_chiranjeevi"],
  actressIds: ["actress_saritha"],
  comedianIds: []
},
{
  id: 84,
  title: "Thathayya Premaleelalu",
  year: 1980,
  genre: "Comedy • Drama",
  industry: "Tollywood",
  poster: "images/movies/thathayya_premaleelalu.jpg",
  description: "A humorous story about a father-son duo dealing with love, marriage, and family antics.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_kvasu",
  actorIds: ["actor_chiranjeevi"],
  actressIds: ["actress_madhuri"],
  comedianIds: ["comedian_gollapudi"]
},
{
  id: 85,
  title: "Love In Singapore",
  year: 1980,
  genre: "Romance • Drama",
  industry: "Tollywood",
  poster: "images/movies/love_in_singapore.jpg",
  description: "A couple's love story unfolds amidst adventures and challenges in Singapore.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_kvasu",
  actorIds: ["actor_chiranjeevi"],
  actressIds: ["actress_saritha"],
  comedianIds: []
},
{
  id: 86,
  title: "Prema Tarangalu",
  year: 1980,
  genre: "Romance • Drama",
  industry: "Tollywood",
  poster: "images/movies/prema_tarangalu.jpg",
  description: "A tale of young love, misunderstandings, and reconciliation between two lovers.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_kvasu",
  actorIds: ["actor_chiranjeevi"],
  actressIds: ["actress_madhuri"],
  comedianIds: []
},
{
  id: 87,
  title: "Mogudu Kaavali",
  year: 1980,
  genre: "Action • Drama",
  industry: "Tollywood",
  poster: "images/movies/mogudu_kaavali.jpg",
  description: "A man fights against a powerful villain to save his village and win the heart of his beloved.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_kvasu",
  actorIds: ["actor_chiranjeevi"],
  actressIds: ["actress_saritha"],
  comedianIds: []
},
{
  id: 88,
  title: "Rakta Bandham",
  year: 1980,
  genre: "Action • Drama",
  industry: "Tollywood",
  poster: "images/movies/rakta_bandham.jpg",
  description: "A story of brotherhood, revenge, and loyalty as brothers unite to defeat their enemies.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_kvasu",
  actorIds: ["actor_chiranjeevi"],
  actressIds: ["actress_madhuri"],
  comedianIds: []
},
{
  id: 89,
  title: "Nyayam Kavali",
  year: 1981,
  genre: "Action • Drama",
  industry: "Tollywood",
  poster: "images/movies/nyayam_kavali.jpg",
  description: "A lawyer fights for justice against corrupt officials and criminals in a gripping courtroom drama.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_kvasu",
  actorIds: ["actor_chiranjeevi"],
  actressIds: ["actress_saritha"],
  comedianIds: []
},
{
  id: 90,
  title: "Ooriki Ichina Maata",
  year: 1981,
  genre: "Action • Drama",
  industry: "Tollywood",
  poster: "images/movies/ooriki_ichina_maata.jpg",
  description: "A man returns to his village to uncover a conspiracy and protect his family from harm.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_kvasu",
  actorIds: ["actor_chiranjeevi"],
  actressIds: ["actress_madhuri"],
  comedianIds: []
},
{
  id: 91,
  title: "Srirasthu Subhamasthu",
  year: 1981,
  genre: "Comedy • Drama",
  industry: "Tollywood",
  poster: "images/movies/srirasthu_subhamasthu.jpg",
  description: "A light-hearted story about a man's quest for happiness and his comedic encounters with family and friends.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_kvasu",
  actorIds: ["actor_chiranjeevi"],
  actressIds: ["actress_saritha"],
  comedianIds: ["comedian_gollapudi"]
},
{
  id: 92,
  title: "Rani Kasula Rangamma",
  year: 1981,
  genre: "Action • Drama",
  industry: "Tollywood",
  poster: "images/movies/rani_kasula_rangamma.jpg",
  description: "A woman fights against oppression and injustice in her community, becoming a symbol of strength.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_kvasu",
  actorIds: ["actor_chiranjeevi"],
  actressIds: ["actress_saritha"],
  comedianIds: []
},
{
  id: 93,
  title: "47 Rojulu",
  year: 1981,
  genre: "Action • Drama",
  industry: "Tollywood",
  poster: "images/movies/47_rojulu.jpg",
  description: "A man is imprisoned for 47 days and upon release, seeks revenge against those who framed him.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_kvasu",
  actorIds: ["actor_chiranjeevi"],
  actressIds: ["actress_madhuri"],
  comedianIds: []
},
{
  id: 94,
  title: "Adavaallu Meeku Joharlu",
  year: 1981,
  genre: "Comedy • Drama",
  industry: "Tollywood",
  poster: "images/movies/adavaallu_meeku_joharlu.jpg",
  description: "A comedic tale of a man who disguises himself to win back his love and resolve family disputes.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_kvasu",
  actorIds: ["actor_chiranjeevi"],
  actressIds: ["actress_saritha"],
  comedianIds: ["comedian_gollapudi"]
},
{
  id: 95,
  title: "Todu Dongalu",
  year: 1981,
  genre: "Action • Drama",
  industry: "Tollywood",
  poster: "images/movies/todu_dongalu.jpg",
  description: "Two thieves with contrasting values get entangled in crime, rivalry, and redemption.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_kvasu",
  actorIds: ["actor_chiranjeevi"],
  actressIds: ["actress_saritha"],
  comedianIds: []
},
{
  id: 96,
  title: "Tiruguleni Manishi",
  year: 1981,
  genre: "Action • Drama",
  industry: "Tollywood",
  poster: "images/movies/tiruguleni_manishi.jpg",
  description: "A man discovers his true identity and embarks on a mission to avenge his past while protecting his loved ones.",
  trailer: "https://www.youtube.com/watch?v=example_trailer",
  directorId: "dir_kvasu",
  actorIds: ["actor_chiranjeevi"],
  actressIds: ["actress_madhuri"],
  comedianIds: []
},
  {
    "id": 97,
    "title": "Subhalekha",
    "year": 1982,
    "genre": "Romance • Drama",
    "industry": "Tollywood",
    "poster": "images/movies/subhalekha.jpg",
    "description": "A progressive love story that challenges social customs surrounding dowry and marriage.",
    "trailer": "https://www.youtube.com/watch?v=example_trailer",
    "directorId": "dir_kviswanath",
    "actorIds": ["actor_chiranjeevi"],
    "actressIds": ["actress_saritha"],
    "comedianIds": []
  },
  {
    "id": 98,
    "title": "Intlo Ramayya Veedilo Krishnayya",
    "year": 1982,
    "genre": "Comedy • Drama",
    "industry": "Tollywood",
    "poster": "images/movies/intlo_ramayya_veedilo_krishnayya.jpg",
    "description": "A light-hearted family drama filled with humor, misunderstandings, and emotional bonding.",
    "trailer": "https://www.youtube.com/watch?v=example_trailer",
    "directorId": "dir_kvasu",
    "actorIds": ["actor_chiranjeevi"],
    "actressIds": ["actress_saritha"],
    "comedianIds": ["comedian_gollapudi"]
  },
  {
    "id": 99,
    "title": "Bandhalu Anubandhalu",
    "year": 1982,
    "genre": "Drama",
    "industry": "Tollywood",
    "poster": "images/movies/bandhalu_anubandhalu.jpg",
    "description": "An emotional drama highlighting relationships, sacrifices, and family values.",
    "trailer": "https://www.youtube.com/watch?v=example_trailer",
    "directorId": "dir_kvasu",
    "actorIds": ["actor_chiranjeevi"],
    "actressIds": ["actress_madhuri"],
    "comedianIds": []
  },
  {
    "id": 100,
    "title": "Idi Pellantara",
    "year": 1982,
    "genre": "Action • Drama",
    "industry": "Tollywood",
    "poster": "images/movies/idi_pellantara.jpg",
    "description": "A socially conscious film questioning the institution of marriage and dowry practices.",
    "trailer": "https://www.youtube.com/watch?v=example_trailer",
    "directorId": "dir_kvasu",
    "actorIds": ["actor_chiranjeevi"],
    "actressIds": ["actress_saritha"],
    "comedianIds": []
  },
  {
    "id": 101,
    "title": "Mondi Ghatam",
    "year": 1982,
    "genre": "Comedy • Drama",
    "industry": "Tollywood",
    "poster": "images/movies/mondi_ghatam.jpg",
    "description": "A situational comedy where a clever man uses wit to escape trouble and create laughter.",
    "trailer": "https://www.youtube.com/watch?v=example_trailer",
    "directorId": "dir_kvasu",
    "actorIds": ["actor_chiranjeevi"],
    "actressIds": ["actress_madhuri"],
    "comedianIds": ["comedian_gollapudi"]
  },
  {
    "id": 102,
    "title": "Manchu Pallaki",
    "year": 1982,
    "genre": "Romance • Drama",
    "industry": "Tollywood",
    "poster": "images/movies/manchu_pallaki.jpg",
    "description": "A sensitive romantic drama exploring love, emotions, and personal sacrifices.",
    "trailer": "https://www.youtube.com/watch?v=example_trailer",
    "directorId": "dir_kvasu",
    "actorIds": ["actor_chiranjeevi"],
    "actressIds": ["actress_saritha"],
    "comedianIds": []
  },
  {
    "id": 103,
    "title": "Yamakinkarudu",
    "year": 1982,
    "genre": "Fantasy • Action",
    "industry": "Tollywood",
    "poster": "images/movies/yamakinkarudu.jpg",
    "description": "A fantasy entertainer where divine forces intervene to punish evil and restore justice.",
    "trailer": "https://www.youtube.com/watch?v=example_trailer",
    "directorId": "dir_kvasu",
    "actorIds": ["actor_chiranjeevi"],
    "actressIds": ["actress_madhuri"],
    "comedianIds": []
  },
  {
    "id": 104,
    "title": "Khaidi",
    "year": 1983,
    "genre": "Action • Drama",
    "industry": "Tollywood",
    "poster": "images/movies/khaidi.jpg",
    "description": "A revolutionary action drama about an innocent man turning rebel against oppression.",
    "trailer": "https://www.youtube.com/watch?v=example_trailer",
    "directorId": "dir_kvasu",
    "actorIds": ["actor_chiranjeevi"],
    "actressIds": ["actress_saritha"],
    "comedianIds": []
  },
  {
    "id": 105,
    "title": "Abhilasha",
    "year": 1983,
    "genre": "Crime • Drama",
    "industry": "Tollywood",
    "poster": "images/movies/abhilasha.jpg",
    "description": "A bold crime drama advocating legal reforms while blending romance and suspense.",
    "trailer": "https://www.youtube.com/watch?v=example_trailer",
    "directorId": "dir_kviswanath",
    "actorIds": ["actor_chiranjeevi"],
    "actressIds": ["actress_saritha"],
    "comedianIds": []
  },
  {
    id: 106,
    title: "Jagadeka Veerudu Atiloka Sundari",
    year: 1990,
    genre: "Fantasy • Adventure • Romance",
    industry: "Tollywood",
    poster: "images/movies/jagadeka_veerudu_atiloka_sundari.jpg",
    description:
      "A fearless adventurer crosses paths with a celestial woman, leading to a magical tale of love and destiny.",
    trailer: "https://www.youtube.com/watch?v=example_trailer",
    directorId: "dir_k_raghavendra_rao",
    actorIds: ["actor_chiranjeevi"],
    actressIds: ["actress_sridevi"],
    comedianIds: []
  },

  {
    id: 107,
    title: "Rudranetra",
    year: 1989,
    genre: "Action • Thriller",
    industry: "Tollywood",
    poster: "images/movies/rudranetra.jpg",
    description:
      "An intense action drama where a determined man fights corruption and criminal conspiracies.",
    trailer: "https://www.youtube.com/watch?v=example_trailer",
    directorId: "dir_k_raghavendra_rao",
    actorIds: ["actor_chiranjeevi"],
    actressIds: ["actress_radha"],
    comedianIds: []
  },

  {
    id: 108,
    title: "Lankeshwarudu",
    year: 1989,
    genre: "Action • Drama",
    industry: "Tollywood",
    poster: "images/movies/lankeshwarudu.jpg",
    description:
      "A powerful leader confronts injustice and moral dilemmas while protecting his people.",
    trailer: "https://www.youtube.com/watch?v=example_trailer",
    directorId: "dir_k_raghavendra_rao",
    actorIds: ["actor_chiranjeevi"],
    actressIds: ["actress_radha"],
    comedianIds: []
  },

  {
    id: 109,
    title: "State Rowdy",
    year: 1989,
    genre: "Action • Crime",
    industry: "Tollywood",
    poster: "images/movies/state_rowdy.jpg",
    description:
      "A feared rowdy transforms into a crusader against crime and political corruption.",
    trailer: "https://www.youtube.com/watch?v=example_trailer",
    directorId: "dir_b_gopal",
    actorIds: ["actor_chiranjeevi"],
    actressIds: ["actress_radha"],
    comedianIds: []
  },

  {
    id: 110,
    title: "Kodama Simham",
    year: 1990,
    genre: "Action • Drama",
    industry: "Tollywood",
    poster: "images/movies/kodama_simham.jpg",
    description:
      "A fearless tribal warrior rises to protect his land and people from ruthless enemies.",
    trailer: "https://www.youtube.com/watch?v=example_trailer",
    directorId: "dir_k_raghavendra_rao",
    actorIds: ["actor_chiranjeevi"],
    actressIds: ["actress_radha"],
    comedianIds: []
  },

  {
    id: 116,
    title: "Gharana Mogudu",
    year: 1992,
    genre: "Action • Comedy",
    industry: "Tollywood",
    poster: "images/movies/gharana_mogudu.jpg",
    description:
      "A bold man stands up against a powerful matriarch to protect workers and restore justice.",
    trailer: "https://www.youtube.com/watch?v=example_trailer",
    directorId: "dir_k_raghavendra_rao",
    actorIds: ["actor_chiranjeevi"],
    actressIds: ["actress_nagma"],
    comedianIds: []
  },

  {
    id: 117,
    title: "Aapadbandhavudu",
    year: 1992,
    genre: "Drama",
    industry: "Tollywood",
    poster: "images/movies/aapadbandhavudu.jpg",
    description:
      "A compassionate man helps a mentally challenged woman rediscover dignity and happiness.",
    trailer: "https://www.youtube.com/watch?v=example_trailer",
    directorId: "dir_k_viswanath",
    actorIds: ["actor_chiranjeevi"],
    actressIds: ["actress_meenakshi_seshadri"],
    comedianIds: []
  },

  {
    id: 118,
    title: "Mutha Mestri",
    year: 1993,
    genre: "Action • Drama",
    industry: "Tollywood",
    poster: "images/movies/mutha_mestri.jpg",
    description:
      "A fearless labor leader rises against corruption and political oppression.",
    trailer: "https://www.youtube.com/watch?v=example_trailer",
    directorId: "dir_k_raghavendra_rao",
    actorIds: ["actor_chiranjeevi"],
    actressIds: ["actress_meena"],
    comedianIds: []
  },

  {
    id: 119,
    title: "Mechanic Alludu",
    year: 1993,
    genre: "Action • Comedy",
    industry: "Tollywood",
    poster: "images/movies/mechanic_alludu.jpg",
    description:
      "A clever mechanic outwits a greedy businessman to protect his family and village.",
    trailer: "https://www.youtube.com/watch?v=example_trailer",
    directorId: "dir_b_gopal",
    actorIds: ["actor_chiranjeevi"],
    actressIds: ["actress_vijayashanti"],
    comedianIds: []
  },

  {
    id: 120,
    title: "Kondaveeti Donga",
    year: 1990,
    genre: "Action • Drama",
    industry: "Tollywood",
    poster: "images/movies/kondaveeti_donga.jpg",
    description:
      "A revolutionary outlaw fights feudal oppression and becomes a symbol of resistance.",
    trailer: "https://www.youtube.com/watch?v=example_trailer",
    directorId: "dir_k_raghavendra_rao",
    actorIds: ["actor_chiranjeevi"],
    actressIds: ["actress_radha"],
    comedianIds: []
  },

  {
    id: 121,
    title: "Hitler",
    year: 1997,
    genre: "Action • Drama",
    industry: "Tollywood",
    poster: "images/movies/hitler.jpg",
    description:
      "A strict elder brother becomes a feared protector of his family and neighborhood.",
    trailer: "https://www.youtube.com/watch?v=example_trailer",
    directorId: "dir_muthyala_subbaiah",
    actorIds: ["actor_chiranjeevi"],
    actressIds: ["actress_rambha"],
    comedianIds: []
  },

  {
    id: 122,
    title: "Indra",
    year: 2002,
    genre: "Action • Drama",
    industry: "Tollywood",
    poster: "images/movies/indra.jpg",
    description:
      "A faction leader returns from exile to restore peace and honor in his homeland.",
    trailer: "https://www.youtube.com/watch?v=example_trailer",
    directorId: "dir_b_gopal",
    actorIds: ["actor_chiranjeevi"],
    actressIds: ["actress_sonali_bendre"],
    comedianIds: []
  },

  {
    id: 123,
    title: "Tagore",
    year: 2003,
    genre: "Action • Drama",
    industry: "Tollywood",
    poster: "images/movies/tagore.jpg",
    description:
      "A vigilante wages war against corruption using intelligence and strategy.",
    trailer: "https://www.youtube.com/watch?v=example_trailer",
    directorId: "dir_v_v_vinayak",
    actorIds: ["actor_chiranjeevi"],
    actressIds: ["actress_jyothika"],
    comedianIds: []
  },

  {
    id: 124,
    title: "Shankar Dada MBBS",
    year: 2004,
    genre: "Comedy • Drama",
    industry: "Tollywood",
    poster: "images/movies/shankar_dada_mbbs.jpg",
    description:
      "A goon pretends to be a doctor and ends up reforming a rigid hospital system.",
    trailer: "https://www.youtube.com/watch?v=example_trailer",
    directorId: "dir_jayanth_c_paranji",
    actorIds: ["actor_chiranjeevi"],
    actressIds: ["actress_genelia"],
    comedianIds: ["comedian_sunil"]
  },

  {
    id: 125,
    title: "Stalin",
    year: 2006,
    genre: "Action • Drama",
    industry: "Tollywood",
    poster: "images/movies/stalin.jpg",
    description:
      "A man believes in helping one person every day, triggering a chain of social change.",
    trailer: "https://www.youtube.com/watch?v=example_trailer",
    directorId: "dir_a_r_murugadoss",
    actorIds: ["actor_chiranjeevi"],
    actressIds: ["actress_trisha"],
    comedianIds: []
  },

  {
    id: 126,
    title: "Shankar Dada Zindabad",
    year: 2007,
    genre: "Comedy • Drama",
    industry: "Tollywood",
    poster: "images/movies/shankar_dada_zindabad.jpg",
    description:
      "A reformed man spreads Gandhian values with humor and compassion.",
    trailer: "https://www.youtube.com/watch?v=example_trailer",
    directorId: "dir_prabhudeva",
    actorIds: ["actor_chiranjeevi"],
    actressIds: ["actress_kareena_kapoor"],
    comedianIds: ["comedian_sunil"]
  },

  {
    id: 127,
    title: "Khaidi No. 150",
    year: 2017,
    genre: "Action • Drama",
    industry: "Tollywood",
    poster: "images/movies/khaidi_no_150.jpg",
    description:
      "A man fights corporate exploitation of farmers by assuming another’s identity.",
    trailer: "https://www.youtube.com/watch?v=example_trailer",
    directorId: "dir_v_v_vinayak",
    actorIds: ["actor_chiranjeevi"],
    actressIds: ["actress_kajal_aggarwal"],
    comedianIds: []
  },

  {
    id: 128,
    title: "Sye Raa Narasimha Reddy",
    year: 2019,
    genre: "Historical • Action",
    industry: "Tollywood",
    poster: "images/movies/sye_raa_narasimha_reddy.jpg",
    description:
      "A legendary freedom fighter leads a rebellion against British rule.",
    trailer: "https://www.youtube.com/watch?v=example_trailer",
    directorId: "dir_surender_reddy",
    actorIds: ["actor_chiranjeevi"],
    actressIds: ["actress_nayanthara"],
    comedianIds: []
  },

  {
    id: 129,
    title: "Acharya",
    year: 2022,
    genre: "Action • Drama",
    industry: "Tollywood",
    poster: "images/movies/acharya.jpg",
    description:
      "A social reformer fights corruption rooted in temple administration.",
    trailer: "https://www.youtube.com/watch?v=example_trailer",
    directorId: "dir_koratala_siva",
    actorIds: ["actor_chiranjeevi"],
    actressIds: ["actress_pooja_hegde"],
    comedianIds: []
  },

  {
    id: 130,
    title: "Waltair Veerayya",
    year: 2023,
    genre: "Action • Drama",
    industry: "Tollywood",
    poster: "images/movies/waltair_veerayya.jpg",
    description:
      "A fisherman-turned-smuggler takes on an international drug syndicate.",
    trailer: "https://www.youtube.com/watch?v=example_trailer",
    directorId: "dir_bobby",
    actorIds: ["actor_chiranjeevi"],
    actressIds: ["actress_shruti_haasan"],
    comedianIds: []
  },

  {
    id: 131,
    title: "Bhola Shankar",
    year: 2023,
    genre: "Action • Comedy",
    industry: "Tollywood",
    poster: "images/movies/bhola_shankar.jpg",
    description:
      "A doting brother with a mysterious past protects his sister from danger.",
    trailer: "https://www.youtube.com/watch?v=example_trailer",
    directorId: "dir_meher_ramesh",
    actorIds: ["actor_chiranjeevi"],
    actressIds: ["actress_kavya_thapar"],
    comedianIds: ["comedian_sunil"]
  }
 ]
};

// Helper function to get director by ID
window.getDirector = function(id) {
  return window.MovieManiacData.directors.find(d => d.id === id);
};

// Helper function to get actor by ID
window.getActor = function(id) {
  return window.MovieManiacData.actors.find(a => a.id === id);
};

// Helper function to get actress by ID
window.getActress = function(id) {
  return window.MovieManiacData.actresses.find(a => a.id === id);
};

// Helper function to get comedian by ID
window.getComedian = function(id) {
  return window.MovieManiacData.comedians.find(c => c.id === id);
};

// Helper function to get movie by ID
window.getMovie = function(id) {
  return window.MovieManiacData.movies.find(m => m.id === parseInt(id));
};

// Helper function to get movies by actor
window.getMoviesByActor = function(actorId) {
  return window.MovieManiacData.movies.filter(m => 
    m.actorIds && m.actorIds.includes(actorId)
  );
};

// Helper function to get movies by actress
window.getMoviesByActress = function(actressId) {
  return window.MovieManiacData.movies.filter(m => 
    m.actressIds && m.actressIds.includes(actressId)
  );
};

// Helper function to get movies by comedian
window.getMoviesByComedian = function(comedianId) {
  return window.MovieManiacData.movies.filter(m => 
    m.comedianIds && m.comedianIds.includes(comedianId)
  );
};

// Helper function to get movies by director
window.getMoviesByDirector = function(directorId) {
  return window.MovieManiacData.movies.filter(m => 
    m.directorId === directorId
  );
}; 